name: ScienceTree
version: ${project.version}
author: Nocturus
description: ScienceTree is a Slimefun addon that replaces the XP research system with a tech tree using research points. Inspired by Factorio, it encourages factory building and slows down progression, adding depth and an industrial feel to your Slimefun experience.
website: https://github.com/LordDarkValk/ScienceTree

main: me.nocturus.sciencetree.ScienceTree
depend: [Slimefun]

api-version: 1.14